volumes:
  ntfy_data:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=UTC    # optional: set desired timezone
    #user: UID:GID # optional: replace with your own user/group or uid/gid

    volumes:
      #- /var/cache/ntfy:/var/cache/ntfy
      #- /etc/ntfy:/etc/ntfy
      - ntfy_data:/var/cache/ntfy
      - ./ntfy.yml:/etc/ntfy/ntfy.yml
      # La riga sopra monta il file di configurazione      
    networks:
      - reverse-proxy      
    ports:
      - 8000:80
    restart: unless-stopped